name: MagicArena
version: '${project.version}'
main: net.pullolo.magicarena.MagicArena
api-version: 1.20
commands:
  createworld:
    usage: /<command> <worldName>
    permission: ma.worlds
    description: Creates a world
  deleteworld:
    usage: /<command> <worldName>
    permission: ma.worlds
    description: Deletes a world
  copyworld:
    usage: /<command> <worldName> <newWorldName>
    permission: ma.worlds
    description: Copies a world
  worlds:
    usage: /<command> <list/tp> <worldName>
    permission: ma.worlds
    description: Lists or teleports you to certain worlds
  gui:
    usage: /<command> <open> <guiName>
    permission: ma.guis
    description: Test guis
  arenas:
    usage: /<command> <save/edit/remove> <world/arena>
    permission: ma.worlds
    description: Manage Arenas
  dungeons:
    usage: /<command> <save/edit/remove> <world/dungeon>
    permission: ma.worlds
    description: Manage Dungeons
  queue:
    usage: /<command> <solo/duo/trio/squad/team/list>
    description: Queue up for a game
  stats:
    usage: /<command> <player>
    description: Displays your stats in a game
  kill:
    usage: /<command> <player>
    permission: ma.kill
    description: Kills a player
  game:
    usage: /<command> <start/end> <type>
    permission: ma.games
    description: Used to test the game
  giveitem:
    usage: /<command>
    permission: ma.items
    description: Gives u custom items
  givearmor:
    usage: /<command>
    permission: ma.items
    description: Gives u custom armors
  spawn:
    usage: /<command> <mob> <level> <?dummy>
    permission: ma.spawn
    description: Spawns a mob at ur location
  party:
    usage: /<command> <cmd> <player>
    description: Manage parties
    aliases:
      - p
  dungeon:
    usage: /<command> <lvl>
    description: Play dungeons (You need to be in a party)
  getskull:
    usage: /<command> <base64>
    permission: ma.items
    description: Gives you a skull
  setcustomname:
    usage: /<command> <name>
    permission: ma.mobs
    description: Names a mob
  getcustomname:
    usage: /<command> <name>
    permission: ma.mobs
    description: Gives you a name of a mob
  data:
    usage: /<command> args...
    permission: ma.data
    description: Let's you modify player data
  open:
    usage: /<command> <chest> args...
    permission: ma.items
    description: Let's you open chests
