name: MagicArena
version: '${project.version}'
main: net.pullolo.magicarena.MagicArena
api-version: 1.20
commands:
  createworld:
    usage: /<command> <worldName>
    permission: ma.worlds
  deleteworld:
    usage: /<command> <worldName>
    permission: ma.worlds
  copyworld:
    usage: /<command> <worldName> <newWorldName>
    permission: ma.worlds