name: MagicArena
version: '${project.version}'
main: net.pullolo.magicarena.MagicArena
api-version: 1.20
commands:
  createworld:
    usage: /<command> <worldName>
    permission: ma.worlds
  deleteworld:
    usage: /<command> <worldName>
    permission: ma.worlds
  copyworld:
    usage: /<command> <worldName> <newWorldName>
    permission: ma.worlds
  worlds:
    usage: /<command> <list/tp> <worldName>
    permission: ma.worlds
  gui:
    usage: /<command> <open> <guiName>
    permission: ma.guis
  arenas:
    usage: /<command> <save/edit/remove> <world/arena>
    permission: ma.worlds
  queue:
    usage: /<command> <solo/duo/trio/squad/team/list>